tsdata<- read.table(choose.files(), header = T, sep = ",")

myts<- ts(tsdata$Sales, start = c(2008,1), end = c(2011,4), frequency = 4)
View(myts)
plot(myts)
library(forecast)
require(forecast)
fit<- ets(myts)
accuracy(fit)
plot(forecast(fit, 4))
fit1<- auto.arima(myts)
accuracy(fit1)
plot(forecast(fit1, 4))
rm(list=ls())
